### ISSUE TITLE
make it work with MAMP

### ISSUE THREAD

**Issue by hirasso** [meodai/mod_autoindex.oh#16]
Hi there, just wanted to know if this also works in combination with MAMP?

**Comment by meodai** [comment]
@hirasso Never tried it. But this should be doable. So would you like to use it for all your mamp prjects, or only selected ones?

**Comment by meodai** [comment]
Did some googleing: https://github.com/jozefizso/mamp/blob/master/apache/conf/extra/httpd-autoindex.conf

So autoindex is enabled on mamp. You could simply place it in your project folder, or edit your gobal file.

**Comment by hirasso** [comment]
Yes I want to have it for all my MAMP projects... So, how would I go about it? Would I just have to overwrite this file with your file that is configured like you say under "Global Installation" ? Sorry, I really don't have any idea about server configs ;(

**Comment by meodai** [comment]
Me neither ;) Yeah that what I would have tried.

PS: if you are a OSX user I don't see why you even need MAMP though.

**Comment by hirasso** [comment]
I use MAMP for its mysql skills. What I have found so far: you have to uncomment line `563` of `MAMP/conf/apache/httpd.conf`, so that MAMP actually uses it.
```
Include /Applications/MAMP/conf/apache/extra/httpd-autoindex.conf
```

**Comment by meodai** [comment]
downloading mamp now ;)

**Comment by hirasso** [comment]
actually, it seems to not even need the mod_autoindex file. I just put the .htaccess file .theme folder you provided to my root folder and removed the `/($folder)` entries inside the .htaccess. Works now! :)

**Comment by meodai** [comment]
super cool! Would you like to edit the readme to add instructions for mamp ?

**Comment by hirasso** [comment]
Would you mind testing the same thing on your machine first? Not that I have missed something...

**Comment by meodai** [comment]
I did it works.
